language: clojure
lein: lein2
jdk:
  - oraclejdk8
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.m2

env:
  global:
    - CDN_BUCKET=cdn.aidbox
    - secure: "X/arLMH/m3GKRMKRzlbsOe+tAEZpxSbcVzDC1q7MQigI4xkqraLP1mvn8ULNPYlpRoAZbbCM3qbuTT9qeEXylseW1XDGXHccbf7QmxT+AvkPL4iv9UwWb4VE3P6KdvaSLgqT3BgCYZV1wZzJMF6MRoq7MXeREROJGquLtpxXwuD5Tm0tFI22jqEBGnArF2Rp2SrBDzzh23dOXUe0mYQi9AocCHl0de8IAdW+GILrclwSQ4FwHMlmAO1vUvotUryD4GXhKwgViEfeVjcQvfy3tcQsXxKdc3pAQGxoCTWFC3R3kVucA3YFNE25XMHTVgZJuEibYBEMVxl6xqgfPKANowcYKal9GnwwNb9MMWiO9CVhMF4cjcuxoxLVvPyKw0o+c4XVCROLZ6bnljYQTWNdG79Tqy4dWEKRZVTEOC+eaGlruITPKrp73Pbd69tXHxFdS6HOyqqxgWzaQcfqIYEL6fU+VjShV0BwbtYcXG9F2aDm4jEDMz1rhPq0uFQRSStMsKwJPsAP2h+u8XBDUocSza7cmmje8rIHt+Z6CUtt75Dp+zQdhBJrhxQ0jkzHtoUtMZqGkPLjlNkMmp+0evctD5n1+Ksbhjp+HFW0gHdTPpJTJ1cDm9V1nG+lk/HRrFf6fwzkPKyOT8O8PvkjASfWmRLlArXmfFdoxR9SEyNfX+A="
    - secure: "CzhId+wQevBuQXuUzFZSfIS/9T2sZEpQuYYimyhJXb4XLELX6GA6aGJXlV6gq/mNiK5wG0EkyJ4Gyy8oL+IStZ0X01ryif+itCfWXdDRUPxdfLnXjcoQekVKjaEnlbH79/Qmhg55TpDP7Vqtsyc36/Hqwj780V6CzCHODcVlH9oZ9eoZBzvDOfcdThOL4rmqt4s3tqvloojjZLGscp/OrSIkaB+grgfRbiw7uDWpPv69yH3XuPxAhHKOcm6H0XlmTJQfG7hHPm2gUjzyfnBxoMVGPAKWufgykeJfxDqblFG04ytYVrpBeIcl7+VF1QntwDLkK1S82UwAhe/5ONwrbYMKhL1Wyg7vmue1aj2lYT4wNShQnx+a0/JLkR8YRK+EGp9FhrA/4DCbB3rOHzmYfljYMCcx6wtO5YDh4koE+Cyl7ALSOo+FWuAlzWLgOwL0v87fF+zBA+RkyrEEVExXIRGSulY211jL9rmi71IophTYaZcs9nZRrqOdQQFv99rH5XD7MdgLmpZUD4dnIMJUxBp3w+Fb+3qw44oheEM33e3wfDswI0UCGnLBTDhGbXewA9kJC6fDoWtJIfiQuR8rZ2KPfMKjDz6pZxjwao2UdBTrCRkg0hvk9EQvPBPxHJB1RHF68TzoVhM9hMKneDu8Tp1VEpiXmvasu2m0Kv9d/Yw="
    - secure: "OdKUllxDHpoZdEAsAjp68iffgPGco1YSgTVPdvjfVDe7SnH1eVuJmgrSaZAFIEpQN+cb1lwfzqfXNV5ApXUvUIGamz6w/aaNEZDz0d4m8QmghaNAuk7Ex5p9ljR3zCRqoWnafkM0/cuA0k+7774gPl9S+dIboBSYbtJ4WWLLT3vwV0nzfISeBPU1C18QXaFjzyPv+j5V9035hl5CMYEEhpnJyMboosDauHRSCe+Jfpfl9nYPMTC2aZINZgGWqLW0t9ZsfAJhHJxZA7ZL5xBERONcvvryzMYjSQA+gH5LUg4XXo8zqUi3yLiKBuU44whn3cPhFK3ylwfIX2fkqmQog0ql0q/M5r3jSkxsFb4zrkAt7kfEtxyMvg9ERyNH5EVmSMPOnhRecq2A8R2p9HiMhIanNBwiF+Hv8R68GWl2p5mXxJaeQOt3TfGhgrVj0iW0O9oSQPNRIl/QPil+Y8RvNvXV5Rg3E7EGZCyvYhx6DWmqIhecOPxLhnPN7lzKuTpdP1yjeCawSlGKiFtqqsUc0Z1R29GquopdkoE/98AKTQiT2gpfgvQWkS/gyS/foOyTfO6RNy0ICkoQVdV6oGJ4MSPdu1Vp5Wq1pmzPV2O3tjMtSpBCDFIUDk1gnoqe64935oVaEKiDMUUFJS/KTsGdZDVf7J4m+zRvf/QSPQ+ct2I="

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

script: |
  set -e &&
  rm -rf dist || exit 0 &&
  mkdir dist &&
  lein generate &&

  aws s3 sync dist s3://$CDN_BUCKET/landing
